spring.application.name=alquilaya

server.port = 1501
spring.datasource.url = jdbc:mysql://localhost:3306/alquilaya?useSSL=false&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password = sistema5
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

app.admin.email = admin@alquilaya.com
app.admin.password = Admin1234

app.operador.email = operador@alquilaya.com
app.operador.password = Operador123
